### ISSUE TITLE
New Perplexity-based NN classes

### ISSUE THREAD

**Issue by cstelmach** [logichris/multi-ann-tsne-widget#3]
Creating new classes based on perplexity-based NN classes, for the sole purpose of redirecting the knn-index building from opentsne to our own method, with the option of selecting one of multiple ann-algorithms.

**Comment by cstelmach** [comment]
Try super()._init_. (beautify code, not needed for functionality).
See if it causes the knn_index to be built twice or still leaves it at once (overwrite, not double initialize)

**Comment by logichris** [comment]
```
class dog():
    def __init__(self):
        init = "Init Base"
        print(init)
        
#currently (full override):
class dug(dog):
    def __init__(self):
        init = "Init Previous"
        print(init)
​
billo = dug()
# **Init Super**  
​
#with super:
class deg(dog):
    def __init__(self):
        super(deg, self).__init__()
        init = "Init Super"
        print(init)

bello = deg()
# **Init Previous**
# **Init Base**
```

**Comment by cstelmach** [comment]
**Base Class:**
```
class base():
    def __init__(self):
        init = "Init Base"
        print(init)
```
        
**Currently (full init override):**
```
class over(base):
    def __init__(self):
        init = "Init Previous"
        print(init)
​
test_fullinit = over()
```
_Init Previous_
​
**Override with super:**
```
class sup(base):
    def __init__(self):
        super(sup, self).__init__()
        init = "Init Super"
        print(init)
​
test_super = sup()
```
_Init Base
Init Super_

---

super (if this is the correct application), would lead to double initialization, thus making in unfeasible.
